services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD= 
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge