services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch.basic.yaml:/usr/share/elasticsearch/config/elasticsearch.yaml
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    mem_limit: 1g

networks:
  elastic:
    driver: bridge