services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge